/* eslint-disable */
// Generated by Wrangler by running `wrangler types`
// Runtime types generated with workerd@1.20260424.1 2025-03-07 nodejs_compat
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		REPORTS_BUCKET: R2Bucket;
		TELEGRAM_SERVICE: Fetcher /* telegram-worker */;
		CF_API_TOKEN_BINDING: string;
		ACCOUNT_ID: string;
	}
}
interface Env extends Cloudflare.Env {}
