/**
 * report-worker — Automated portfolio performance reports via Browser Rendering.
 *
 * Cron-triggered (06:00 UTC + 18:00 UTC):
 * 1. Fetches portfolio data from D1 (via d1-worker service binding)
 * 2. Renders HTML report page
 * 3. Generates PDF via Cloudflare Browser Rendering REST API
 * 4. Stores PDF in R2 bucket
 * 5. Sends notification link via telegram-worker
 */

import type { Fetcher } from "@cloudflare/workers-types";

// --- Types ---

interface Env {
  // R2 bucket for storing generated PDFs
  REPORTS_BUCKET: R2Bucket;
  // Service binding to telegram-worker for notifications
  TELEGRAM_SERVICE: Fetcher;
  // Cloudflare API token with Browser Rendering + R2 write permissions
  CF_API_TOKEN_BINDING: string;
}

interface PortfolioSummary {
  totalValue: number;
  dailyPnL: number;
  totalPnL: number;
  openPositions: number;
  winRate: number;
  topAsset: string;
}

// --- Constants ---

const ACCOUNT_ID = "debc6545e63bea36be059cbc82d80ec8";
const BROWSER_RENDERING_URL = `https://api.cloudflare.com/client/v4/accounts/${ACCOUNT_ID}/browser-rendering`;
const REPORTS_PREFIX = "reports/";

// --- Worker Entry ---

export default {
  async scheduled(
    _controller: ScheduledController,
    env: Env,
    _ctx: ExecutionContext,
  ): Promise<void> {
    try {
      const summary = await fetchPortfolioSummary();
      const html = buildReportHtml(summary);
      const pdfBuffer = await generatePdf(html, env);
      const key = `${REPORTS_PREFIX}daily-${Date.now()}.pdf`;
      await env.REPORTS_BUCKET.put(key, pdfBuffer, {
        httpMetadata: { contentType: "application/pdf" },
      });
      await sendNotification(env, key, summary);
    } catch (err) {
      console.error("[report-worker] Failed to generate report:", err);
    }
  },
};

// --- Helpers ---

async function fetchPortfolioSummary(): Promise<PortfolioSummary> {
  // Stub — in production, query D1 via d1-worker service binding
  return {
    totalValue: 125_000,
    dailyPnL: 1_230,
    totalPnL: 18_500,
    openPositions: 4,
    winRate: 72.5,
    topAsset: "BTC/USDT",
  };
}

function buildReportHtml(summary: PortfolioSummary): string {
  const date = new Date().toISOString().split("T")[0];
  const changeClass = summary.dailyPnL >= 0 ? "positive" : "negative";
  const changeSign = summary.dailyPnL >= 0 ? "+" : "";
  const totalChangeClass = summary.totalPnL >= 0 ? "positive" : "negative";
  const totalChangeSign = summary.totalPnL >= 0 ? "+" : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  body { font-family: -apple-system, system-ui, sans-serif; padding: 2rem; color: #1a1a2e; }
  h1 { color: #16213e; border-bottom: 3px solid #0f3460; padding-bottom: 0.5rem; }
  .date { color: #666; font-size: 0.9em; margin-top: -0.5rem; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; margin: 2rem 0; }
  .card { background: #f8f9fa; border-radius: 8px; padding: 1rem; border: 1px solid #e9ecef; }
  .card h2 { margin: 0 0 0.3rem; font-size: 0.85em; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
  .card .value { font-size: 1.5em; font-weight: 700; margin: 0; }
  .positive { color: #16a34a; }
  .negative { color: #dc2626; }
  .footer { margin-top: 2rem; font-size: 0.8em; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 1rem; }
</style>
</head>
<body>
<h1>Hoox Portfolio Report</h1>
<p class="date">${date}</p>
<div class="grid">
  <div class="card">
    <h2>Total Value</h2>
    <p class="value">$${summary.totalValue.toLocaleString()}</p>
  </div>
  <div class="card">
    <h2>Daily P&L</h2>
    <p class="value ${changeClass}">${changeSign}$${summary.dailyPnL.toLocaleString()}</p>
  </div>
  <div class="card">
    <h2>Total P&L</h2>
    <p class="value ${totalChangeClass}">${totalChangeSign}$${summary.totalPnL.toLocaleString()}</p>
  </div>
  <div class="card">
    <h2>Open Positions</h2>
    <p class="value">${summary.openPositions}</p>
  </div>
  <div class="card">
    <h2>Win Rate</h2>
    <p class="value">${summary.winRate}%</p>
  </div>
  <div class="card">
    <h2>Top Asset</h2>
    <p class="value">${summary.topAsset}</p>
  </div>
</div>
<p style="margin-top: 1rem; color: #444;">Generated by Hoox — Automated Trading System</p>
<div class="footer">
  <p>This report was automatically generated. Past performance does not guarantee future results.</p>
</div>
</body>
</html>`;
}

async function generatePdf(
  html: string,
  env: Env,
): Promise<ArrayBuffer> {
  if (!env.CF_API_TOKEN_BINDING) {
    console.warn("[report-worker] No CF_API_TOKEN — returning text fallback");
    return new TextEncoder().encode("PDF generation requires CF_API_TOKEN").buffer as ArrayBuffer;
  }

  const response = await fetch(
    `${BROWSER_RENDERING_URL}/pdf`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${env.CF_API_TOKEN_BINDING}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        html,
        options: {
          format: "A4",
          printBackground: true,
          margin: { top: "1cm", right: "1cm", bottom: "1cm", left: "1cm" },
        },
      }),
    },
  );

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Browser Rendering API error: ${response.status} — ${text}`);
  }

  return response.arrayBuffer() as Promise<ArrayBuffer>;
}

async function sendNotification(
  env: Env,
  key: string,
  summary: PortfolioSummary,
): Promise<void> {
  if (!env.TELEGRAM_SERVICE) return;

  const signedUrl = `https://report-worker.cryptolinx.workers.dev/${key}`;
  const message = [
    `📊 *Daily Portfolio Report*`,
    ``,
    `Total Value: $${summary.totalValue.toLocaleString()}`,
    `Daily P&L: ${summary.dailyPnL >= 0 ? "+" : ""}$${summary.dailyPnL.toLocaleString()}`,
    `Win Rate: ${summary.winRate}%`,
    ``,
    `[View Report](${signedUrl})`,
  ].join("\n");

  await env.TELEGRAM_SERVICE.fetch(
    new Request("http://telegram-service/process", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        internalAuthKey: "report-worker",
        payload: { message, chatId: undefined },
      }),
    }),
  );
}
